#ifndef REGISTER_APPLICATION_H

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define GENERATE_APP_INFO(NAME, AUTHOR, COLOR, VERSION, VISIBILITY)  Application_Info(NAME, AUTHOR, COLOR, VERSION, VISIBILITY),

#define PUSH_REG_APP_INFOS _Pragma("push_macro(\"REGISTERED_APP_INFOS\")") 
#define POP_REG_APP_INFOS _Pragma("pop_macro(\"REGISTERED_APP_INFOS\")")

#define GENERATE_APP_SWITCH(NAME, AUTHOR, CLASS) case StaticHash(AUTHOR): active_app = new CLASS(); break;

#define PUSH_REG_APP_SWITCH _Pragma("push_macro(\"REGISTERED_APP_SWITCH\")") 
#define POP_REG_APP_SWITCH _Pragma("pop_macro(\"REGISTERED_APP_SWITCH\")")

#define REGISTER_APPLICATION_H
#endif

#ifndef APPLICATION_VERSION
#define APPLICATION_VERSION 0
#endif

#ifndef APPLICATION_VISIBLITY
#define APPLICATION_VISIBLITY false
#endif


PUSH_REG_APP_INFOS
#undef REGISTERED_APP_INFOS
#define REGISTERED_APP_INFOS POP_REG_APP_INFOS REGISTERED_APP_INFOS GENERATE_APP_INFO(TOSTRING(APPLICATION_NAME), TOSTRING(APPLICATION_AUTHOR), TOSTRING(APPLICATION_COLOR), TOSTRING(APPLICATION_VERSION), TOSTRING(APPLICATION_VISIBLITY))

PUSH_REG_APP_SWITCH
#undef REGISTERED_APP_SWITCH
#define REGISTERED_APP_SWITCH POP_REG_APP_SWITCH REGISTERED_APP_SWITCH GENERATE_APP_SWITCH(TOSTRING(APPLICATION_NAME), TOSTRING(APPLICATION_AUTHOR), TOSTRING(APPLICATION_CLASS))

#undef APPLICATION_NAME
#undef APPLICATION_AUTHOR
#undef APPLICATION_COLOR
#undef APPLICATION_VERSION
#undef APPLICATION_VISIBLITY
#undef APPLICATION_CLASS

