#pragma once

#define XSTR(v) STR(v)
#define STR(v) #v

// #define RELEASE 0
// #define INDEV 1
// #define RELEASE_CANDIDATE 2
// #define BETA 3
// #define NIGHTY 4

#if defined(MATRIXOS_BUILD_RELEASE)
#define MATRIXOS_BUILD_VER 0
#define MATRIXOS_LOG_LEVEL  LOG_LEVEL_INFO
#define MATRIXOS_VERSION_STRING XSTR(MATRIXOS_MAJOR_VER) "." XSTR(MATRIXOS_MINOR_VER) "." XSTR(MATRIXOS_PATCH_VER)
#elif defined(MATRIXOS_BUILD_RELEASE_CANDIDATE)
#define MATRIXOS_BUILD_VER 2
#define MATRIXOS_LOG_LEVEL  LOG_LEVEL_INFO
#define MATRIXOS_VERSION_STRING XSTR(MATRIXOS_MAJOR_VER) "." XSTR(MATRIXOS_MINOR_VER) " RC" XSTR(MATRIXOS_PATCH_VER)
#elif defined(MATRIXOS_BUILD_BETA)
#define MATRIXOS_BUILD_VER 3
#define MATRIXOS_LOG_LEVEL  LOG_LEVEL_INFO
#define MATRIXOS_VERSION_STRING XSTR(MATRIXOS_MAJOR_VER) "." XSTR(MATRIXOS_MINOR_VER) " Beta " XSTR(MATRIXOS_PATCH_VER)
#elif defined(MATRIXOS_BUILD_NIGHTY)
#define MATRIXOS_BUILD_VER 4
#define MATRIXOS_LOG_LEVEL  LOG_LEVEL_INFO
#define MATRIXOS_VERSION_STRING XSTR(MATRIXOS_MAJOR_VER) "." XSTR(MATRIXOS_MINOR_VER) "." XSTR(MATRIXOS_PATCH_VER) " Nighty " __DATE__
#elif defined(MATRIXOS_BUILD_INDEV)
#define MATRIXOS_BUILD_VER 1
#define MATRIXOS_LOG_LEVEL  LOG_LEVEL_VERBOSE
#define MATRIXOS_VERSION_STRING XSTR(MATRIXOS_MAJOR_VER) "." XSTR(MATRIXOS_MINOR_VER) " InDev " __DATE__ " " __TIME__
#else
#error "No Release Version Specified"
#endif