#pragma once

#include "MatrixOS.h"
#include "system/USB/USB.h"
#include "tusb_config.h"

namespace MatrixOS::USB
{
  class MIDI : public UsbInterface
  {
    // static vector<MIDI*> midi_interfaces;
    // uint8_t midi_id;
    uint8_t interface_id;
    string interface_name;
    uint8_t cable_nums;
    // MidiPort midi_port;
    // TaskHandle_t port_task;
    list<MidiPort> midi_ports;
    vector<TaskHandle_t> port_tasks;
    uint16_t ep_size;

   public:
    MIDI(string interface_name = "", uint16_t ep_size = CFG_TUD_MIDI_RX_BUFSIZE); // Use "" as interface name will use default string generated by the OS
    MIDI(uint8_t cable_nums, string interface_name = "", uint16_t ep_size = CFG_TUD_MIDI_RX_BUFSIZE); // Use "" as interface name will use default string generated by the OS
    ~MIDI();

    void Begin(void);
    
    private:
    static void PortTask(void* param);
  };
}

void tud_midi_rx_cb(uint8_t itf);