/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_Input__H
#define ___MatrixOS_Input__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_Input(Args *args);

void _MatrixOS_Input_ClearQueue(PikaObj *self);
void _MatrixOS_Input_ClearState(PikaObj *self);
PikaObj* _MatrixOS_Input_FunctionKey(PikaObj *self);
PikaObj* _MatrixOS_Input_GetClusters(PikaObj *self);
Arg* _MatrixOS_Input_GetEvent(PikaObj *self, int timeout_ms);
PikaObj* _MatrixOS_Input_GetInputsAt(PikaObj *self, PikaObj* point);
Arg* _MatrixOS_Input_GetPosition(PikaObj *self, PikaObj* input_id);
Arg* _MatrixOS_Input_GetPrimaryGridCluster(PikaObj *self);
Arg* _MatrixOS_Input_GetState(PikaObj *self, PikaObj* input_id);

#endif
