/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_KeyPad__H
#define ___MatrixOS_KeyPad__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_KeyPad(Args *args);

void _MatrixOS_KeyPad_Clear(PikaObj *self);
Arg* _MatrixOS_KeyPad_Get(PikaObj *self, int timeout_ms);
Arg* _MatrixOS_KeyPad_GetKey(PikaObj *self, PikaObj* keyXY);
Arg* _MatrixOS_KeyPad_GetKeyByID(PikaObj *self, int keyID);
Arg* _MatrixOS_KeyPad_ID2XY(PikaObj *self, int keyID);
int _MatrixOS_KeyPad_XY2ID(PikaObj *self, PikaObj* xy);

#endif
