/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_KeyEvent_KeyEvent__H
#define ___MatrixOS_KeyEvent_KeyEvent__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_KeyEvent_KeyEvent(Args *args);

int _MatrixOS_KeyEvent_KeyEvent_ID(PikaObj *self);
PikaObj* _MatrixOS_KeyEvent_KeyEvent_KeyInfo(PikaObj *self);
void _MatrixOS_KeyEvent_KeyEvent___del__(PikaObj *self);
void _MatrixOS_KeyEvent_KeyEvent___init__(PikaObj *self, int id, PikaObj* info);

#endif
