/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_USB_CDC__H
#define ___MatrixOS_USB_CDC__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_USB_CDC(Args *args);

int _MatrixOS_USB_CDC_Available(PikaObj *self);
pika_bool _MatrixOS_USB_CDC_Connected(PikaObj *self);
void _MatrixOS_USB_CDC_Flush(PikaObj *self);
void _MatrixOS_USB_CDC_Poll(PikaObj *self);
void _MatrixOS_USB_CDC_Print(PikaObj *self, char* text, char* end);
int _MatrixOS_USB_CDC_Read(PikaObj *self);
Arg* _MatrixOS_USB_CDC_ReadBytes(PikaObj *self, int max_length);
char* _MatrixOS_USB_CDC_ReadString(PikaObj *self);

#endif
