/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_Color_Color__H
#define ___MatrixOS_Color_Color__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_Color_Color(Args *args);

PikaObj* _MatrixOS_Color_Color_Dim(PikaObj *self, pika_float factor);
PikaObj* _MatrixOS_Color_Color_DimIfNot(PikaObj *self, pika_bool not_dim, pika_float factor);
PikaObj* _MatrixOS_Color_Color_FromHex(PikaObj *self, int hex);
PikaObj* _MatrixOS_Color_Color_FromRGB(PikaObj *self, int r, int g, int b);
PikaObj* _MatrixOS_Color_Color_FromRGBW(PikaObj *self, int r, int g, int b, int w);
PikaObj* _MatrixOS_Color_Color_Scale(PikaObj *self, pika_float factor);
pika_bool _MatrixOS_Color_Color___eq__(PikaObj *self, PikaObj* other);
void _MatrixOS_Color_Color___init__(PikaObj *self, int r, int g, int b, int w);
pika_bool _MatrixOS_Color_Color___ne__(PikaObj *self, PikaObj* other);

#endif
