/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_UIUtility__H
#define ___MatrixOS_UIUtility__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_UIUtility(Args *args);

Arg* _MatrixOS_UIUtility_ColorPicker(PikaObj *self);
int _MatrixOS_UIUtility_NumberSelector8x8(PikaObj *self, int value, PikaObj* color, char* name, int lower_limit, int upper_limit);
void _MatrixOS_UIUtility_TextScroll(PikaObj *self, char* text, PikaObj* color, int speed, pika_bool loop);

#endif
