/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_KeypadInfo_KeypadInfo__H
#define ___MatrixOS_KeypadInfo_KeypadInfo__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_KeypadInfo_KeypadInfo(Args *args);

pika_bool _MatrixOS_KeypadInfo_KeypadInfo_Active(PikaObj *self);
pika_float _MatrixOS_KeypadInfo_KeypadInfo_Force(PikaObj *self);
pika_bool _MatrixOS_KeypadInfo_KeypadInfo_Hold(PikaObj *self);
int _MatrixOS_KeypadInfo_KeypadInfo_HoldTime(PikaObj *self);
int _MatrixOS_KeypadInfo_KeypadInfo_LastEventTime(PikaObj *self);
int _MatrixOS_KeypadInfo_KeypadInfo_State(PikaObj *self);
pika_float _MatrixOS_KeypadInfo_KeypadInfo_Value(PikaObj *self, int index);
pika_bool _MatrixOS_KeypadInfo_KeypadInfo___bool__(PikaObj *self);
void _MatrixOS_KeypadInfo_KeypadInfo___init__(PikaObj *self);

#endif
