/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_Dimension_Dimension__H
#define ___MatrixOS_Dimension_Dimension__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_Dimension_Dimension(Args *args);

int _MatrixOS_Dimension_Dimension_Area(PikaObj *self);
pika_bool _MatrixOS_Dimension_Dimension_Contains(PikaObj *self, PikaObj* point);
void _MatrixOS_Dimension_Dimension_SetX(PikaObj *self, int x);
void _MatrixOS_Dimension_Dimension_SetY(PikaObj *self, int y);
int _MatrixOS_Dimension_Dimension_X(PikaObj *self);
int _MatrixOS_Dimension_Dimension_Y(PikaObj *self);
PikaObj* _MatrixOS_Dimension_Dimension___add__(PikaObj *self, PikaObj* other);
pika_bool _MatrixOS_Dimension_Dimension___bool__(PikaObj *self);
pika_bool _MatrixOS_Dimension_Dimension___eq__(PikaObj *self, PikaObj* other);
void _MatrixOS_Dimension_Dimension___init__(PikaObj *self, PikaTuple* val);

#endif
