/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_UI_UI__H
#define ___MatrixOS_UI_UI__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_UI_UI(Args *args);

pika_bool _MatrixOS_UI_UI_AddUIComponent(PikaObj *self, PikaObj* uiComponent, PikaObj* xy);
pika_bool _MatrixOS_UI_UI_AllowExit(PikaObj *self, pika_bool allow);
pika_bool _MatrixOS_UI_UI_ClearUIComponents(PikaObj *self);
pika_bool _MatrixOS_UI_UI_SetColor(PikaObj *self, PikaObj* color);
pika_bool _MatrixOS_UI_UI_SetEndFunc(PikaObj *self, Arg* endFunc);
pika_bool _MatrixOS_UI_UI_SetFPS(PikaObj *self, int fps);
pika_bool _MatrixOS_UI_UI_SetKeyEventHandler(PikaObj *self, Arg* key_event_handler);
pika_bool _MatrixOS_UI_UI_SetLoopFunc(PikaObj *self, Arg* loopFunc);
pika_bool _MatrixOS_UI_UI_SetName(PikaObj *self, char* name);
pika_bool _MatrixOS_UI_UI_SetPostRenderFunc(PikaObj *self, Arg* post_renderFunc);
pika_bool _MatrixOS_UI_UI_SetPreRenderFunc(PikaObj *self, Arg* pre_renderFunc);
pika_bool _MatrixOS_UI_UI_SetSetupFunc(PikaObj *self, Arg* setupFunc);
pika_bool _MatrixOS_UI_UI_ShouldCreatenewLEDLayer(PikaObj *self, pika_bool create);
pika_bool _MatrixOS_UI_UI_Start(PikaObj *self);
void _MatrixOS_UI_UI___init__(PikaObj *self, PikaTuple* val);

#endif
