/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS__H
#define ___MatrixOS__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS(Args *args);

void _MatrixOS_Bootloader(PikaObj *self);
void _MatrixOS_DelayMs(PikaObj *self, int ms);
void _MatrixOS_ExecuteAPP(PikaObj *self, char* author, char* app_name);
void _MatrixOS_ExecuteAPPByID(PikaObj *self, int app_id);
Arg* _MatrixOS_KeyPad(PikaObj *self);
Arg* _MatrixOS_LED(PikaObj *self);
int _MatrixOS_Millis(PikaObj *self);
void _MatrixOS_OpenSetting(PikaObj *self);
int _MatrixOS_Test(PikaObj *self, int input);

#endif
