/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_Point_Point__H
#define ___MatrixOS_Point_Point__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_Point_Point(Args *args);

PikaObj* _MatrixOS_Point_Point_Invalid(PikaObj *self);
PikaObj* _MatrixOS_Point_Point_Origin(PikaObj *self);
PikaObj* _MatrixOS_Point_Point_Rotate(PikaObj *self, PikaObj* rotation, PikaObj* dimension, pika_bool reverse);
void _MatrixOS_Point_Point_SetX(PikaObj *self, int x);
void _MatrixOS_Point_Point_SetY(PikaObj *self, int y);
int _MatrixOS_Point_Point_X(PikaObj *self);
int _MatrixOS_Point_Point_Y(PikaObj *self);
PikaObj* _MatrixOS_Point_Point___add__(PikaObj *self, PikaObj* other);
pika_bool _MatrixOS_Point_Point___eq__(PikaObj *self, PikaObj* other);
void _MatrixOS_Point_Point___init__(PikaObj *self, int x, int y);
PikaObj* _MatrixOS_Point_Point___mul__(PikaObj *self, int val);
pika_bool _MatrixOS_Point_Point___ne__(PikaObj *self, PikaObj* other);
PikaObj* _MatrixOS_Point_Point___sub__(PikaObj *self, PikaObj* other);

#endif
