/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_SYS__H
#define ___MatrixOS_SYS__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_SYS(Args *args);

void _MatrixOS_SYS_Bootloader(PikaObj *self);
void _MatrixOS_SYS_DelayMs(PikaObj *self, int ms);
void _MatrixOS_SYS_ExecuteAPP(PikaObj *self, char* author, char* app_name, PikaObj* args);
void _MatrixOS_SYS_ExecuteAPPByID(PikaObj *self, int app_id, PikaObj* args);
PikaObj* _MatrixOS_SYS_GetVersion(PikaObj *self);
int64_t _MatrixOS_SYS_Micros(PikaObj *self);
int64_t _MatrixOS_SYS_Millis(PikaObj *self);
void _MatrixOS_SYS_OpenSetting(PikaObj *self);
void _MatrixOS_SYS_Reboot(PikaObj *self);

#endif
