/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_NVS__H
#define ___MatrixOS_NVS__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_NVS(Args *args);

pika_bool _MatrixOS_NVS_DeleteVariable(PikaObj *self, int hash);
int _MatrixOS_NVS_GetSize(PikaObj *self, int hash);
Arg* _MatrixOS_NVS_GetVariable(PikaObj *self, int hash);
pika_bool _MatrixOS_NVS_SetVariable(PikaObj *self, int hash, uint8_t* data, int length);

#endif
