/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_ColorEffects__H
#define ___MatrixOS_ColorEffects__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_ColorEffects(Args *args);

int _MatrixOS_ColorEffects_Breath(PikaObj *self, PikaObj* period, PikaObj* offset);
int _MatrixOS_ColorEffects_BreathLowBound(PikaObj *self, PikaObj* low_bound, PikaObj* period, PikaObj* offset);
PikaObj* _MatrixOS_ColorEffects_ColorBreath(PikaObj *self, PikaObj* color, PikaObj* period, PikaObj* offset);
PikaObj* _MatrixOS_ColorEffects_ColorBreathLowBound(PikaObj *self, PikaObj* color, PikaObj* low_bound, PikaObj* period, PikaObj* offset);
PikaObj* _MatrixOS_ColorEffects_ColorSaw(PikaObj *self, PikaObj* color, PikaObj* period, PikaObj* offset);
PikaObj* _MatrixOS_ColorEffects_ColorStrobe(PikaObj *self, PikaObj* color, PikaObj* period, PikaObj* offset);
PikaObj* _MatrixOS_ColorEffects_ColorTriangle(PikaObj *self, PikaObj* color, PikaObj* period, PikaObj* offset);
PikaObj* _MatrixOS_ColorEffects_Rainbow(PikaObj *self, PikaObj* period, PikaObj* offset);
int _MatrixOS_ColorEffects_Saw(PikaObj *self, PikaObj* period, PikaObj* offset);
int _MatrixOS_ColorEffects_Strobe(PikaObj *self, PikaObj* period, PikaObj* offset);
int _MatrixOS_ColorEffects_Triangle(PikaObj *self, PikaObj* period, PikaObj* offset);

#endif
