/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_HID_Gamepad__H
#define ___MatrixOS_HID_Gamepad__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_HID_Gamepad(Args *args);

void _MatrixOS_HID_Gamepad_Button(PikaObj *self, int button_id, pika_bool state);
void _MatrixOS_HID_Gamepad_Buttons(PikaObj *self, int button_mask);
void _MatrixOS_HID_Gamepad_DPad(PikaObj *self, PikaObj* direction);
void _MatrixOS_HID_Gamepad_Press(PikaObj *self, int button_id);
void _MatrixOS_HID_Gamepad_RXAxis(PikaObj *self, pika_float value);
void _MatrixOS_HID_Gamepad_RYAxis(PikaObj *self, pika_float value);
void _MatrixOS_HID_Gamepad_RZAxis(PikaObj *self, pika_float value);
void _MatrixOS_HID_Gamepad_Release(PikaObj *self, int button_id);
void _MatrixOS_HID_Gamepad_ReleaseAll(PikaObj *self);
void _MatrixOS_HID_Gamepad_Tap(PikaObj *self, int button_id, int length_ms);
void _MatrixOS_HID_Gamepad_XAxis(PikaObj *self, pika_float value);
void _MatrixOS_HID_Gamepad_YAxis(PikaObj *self, pika_float value);
void _MatrixOS_HID_Gamepad_ZAxis(PikaObj *self, pika_float value);

#endif
