/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_MidiPacket_MidiPacket__H
#define ___MatrixOS_MidiPacket_MidiPacket__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_MidiPacket_MidiPacket(Args *args);

PikaObj* _MatrixOS_MidiPacket_MidiPacket_ActiveSense(PikaObj *self);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_AfterTouch(PikaObj *self, int channel, int note, int pressure);
int _MatrixOS_MidiPacket_MidiPacket_Channel(PikaObj *self);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_ChannelPressure(PikaObj *self, int channel, int pressure);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_Clock(PikaObj *self);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_Continue(PikaObj *self);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_ControlChange(PikaObj *self, int channel, int controller, int value);
int _MatrixOS_MidiPacket_MidiPacket_Controller(PikaObj *self);
int _MatrixOS_MidiPacket_MidiPacket_Length(PikaObj *self);
int _MatrixOS_MidiPacket_MidiPacket_Note(PikaObj *self);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_NoteOff(PikaObj *self, int channel, int note, int velocity);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_NoteOn(PikaObj *self, int channel, int note, int velocity);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_PitchBend(PikaObj *self, int channel, int value);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_Port(PikaObj *self);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_ProgramChange(PikaObj *self, int channel, int program);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_Reset(PikaObj *self);
pika_bool _MatrixOS_MidiPacket_MidiPacket_SetChannel(PikaObj *self, int channel);
pika_bool _MatrixOS_MidiPacket_MidiPacket_SetController(PikaObj *self, int controller);
pika_bool _MatrixOS_MidiPacket_MidiPacket_SetNote(PikaObj *self, int note);
pika_bool _MatrixOS_MidiPacket_MidiPacket_SetStatus(PikaObj *self, PikaObj* status);
pika_bool _MatrixOS_MidiPacket_MidiPacket_SetValue(PikaObj *self, int value);
pika_bool _MatrixOS_MidiPacket_MidiPacket_SetVelocity(PikaObj *self, int velocity);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_SongPosition(PikaObj *self, int position);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_SongSelect(PikaObj *self, int song);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_Start(PikaObj *self);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_Status(PikaObj *self);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_Stop(PikaObj *self);
pika_bool _MatrixOS_MidiPacket_MidiPacket_SysEx(PikaObj *self);
pika_bool _MatrixOS_MidiPacket_MidiPacket_SysExStart(PikaObj *self);
PikaObj* _MatrixOS_MidiPacket_MidiPacket_TuneRequest(PikaObj *self);
int _MatrixOS_MidiPacket_MidiPacket_Value(PikaObj *self);
int _MatrixOS_MidiPacket_MidiPacket_Velocity(PikaObj *self);
void _MatrixOS_MidiPacket_MidiPacket___init__(PikaObj *self, PikaTuple* val);

#endif
