/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_InputId_InputId__H
#define ___MatrixOS_InputId_InputId__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_InputId_InputId(Args *args);

int _MatrixOS_InputId_InputId_ClusterId(PikaObj *self);
PikaObj* _MatrixOS_InputId_InputId_FunctionKey(PikaObj *self);
PikaObj* _MatrixOS_InputId_InputId_Invalid(PikaObj *self);
int _MatrixOS_InputId_InputId_MemberId(PikaObj *self);
pika_bool _MatrixOS_InputId_InputId___bool__(PikaObj *self);
pika_bool _MatrixOS_InputId_InputId___eq__(PikaObj *self, PikaObj* other);
void _MatrixOS_InputId_InputId___init__(PikaObj *self);
pika_bool _MatrixOS_InputId_InputId___ne__(PikaObj *self, PikaObj* other);

#endif
