/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_LED__H
#define ___MatrixOS_LED__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_LED(Args *args);

void _MatrixOS_LED_CopyLayer(PikaObj *self, int dest, int src);
int _MatrixOS_LED_CreateLayer(PikaObj *self, int crossfade);
int _MatrixOS_LED_CurrentLayer(PikaObj *self);
pika_bool _MatrixOS_LED_DestroyLayer(PikaObj *self, int crossfade);
void _MatrixOS_LED_Fade(PikaObj *self, int crossfade);
void _MatrixOS_LED_Fill(PikaObj *self, PikaObj* color, int layer);
pika_bool _MatrixOS_LED_FillPartition(PikaObj *self, char* partition, PikaObj* color, int layer);
int _MatrixOS_LED_GetLEDCount(PikaObj *self);
void _MatrixOS_LED_NextBrightness(PikaObj *self);
void _MatrixOS_LED_PauseUpdate(PikaObj *self, pika_bool pause);
void _MatrixOS_LED_SetBrightness(PikaObj *self, int brightness);
pika_bool _MatrixOS_LED_SetBrightnessMultiplier(PikaObj *self, char* partition_name, pika_float multiplier);
void _MatrixOS_LED_SetColor(PikaObj *self, PikaObj* xy, PikaObj* color, int layer);
void _MatrixOS_LED_SetColorByID(PikaObj *self, int id, PikaObj* color, int layer);
void _MatrixOS_LED_Update(PikaObj *self, int layer);

#endif
