/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_UISelector_UISelector__H
#define ___MatrixOS_UISelector_UISelector__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_UISelector_UISelector(Args *args);

pika_bool _MatrixOS_UISelector_UISelector_OnChange(PikaObj *self, Arg* changeCallback);
pika_bool _MatrixOS_UISelector_UISelector_SetColor(PikaObj *self, PikaObj* color);
pika_bool _MatrixOS_UISelector_UISelector_SetColorFunc(PikaObj *self, Arg* colorFunc);
pika_bool _MatrixOS_UISelector_UISelector_SetCount(PikaObj *self, int count);
pika_bool _MatrixOS_UISelector_UISelector_SetDimension(PikaObj *self, PikaObj* dimension);
pika_bool _MatrixOS_UISelector_UISelector_SetDirection(PikaObj *self, int direction);
pika_bool _MatrixOS_UISelector_UISelector_SetIndividualColorFunc(PikaObj *self, Arg* individualColorFunc);
pika_bool _MatrixOS_UISelector_UISelector_SetLitMode(PikaObj *self, int litMode);
pika_bool _MatrixOS_UISelector_UISelector_SetName(PikaObj *self, char* name);
pika_bool _MatrixOS_UISelector_UISelector_SetNameFunc(PikaObj *self, Arg* nameFunc);
pika_bool _MatrixOS_UISelector_UISelector_SetValueFunc(PikaObj *self, Arg* getValueFunc);
void _MatrixOS_UISelector_UISelector___init__(PikaObj *self);

#endif
