/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_InputCluster_InputCluster__H
#define ___MatrixOS_InputCluster_InputCluster__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_InputCluster_InputCluster(Args *args);

int _MatrixOS_InputCluster_InputCluster_ClusterId(PikaObj *self);
PikaObj* _MatrixOS_InputCluster_InputCluster_Dimension(PikaObj *self);
pika_bool _MatrixOS_InputCluster_InputCluster_HasCoordinates(PikaObj *self);
pika_bool _MatrixOS_InputCluster_InputCluster_HasRootPoint(PikaObj *self);
int _MatrixOS_InputCluster_InputCluster_InputClass(PikaObj *self);
int _MatrixOS_InputCluster_InputCluster_InputCount(PikaObj *self);
char* _MatrixOS_InputCluster_InputCluster_Name(PikaObj *self);
PikaObj* _MatrixOS_InputCluster_InputCluster_RootPoint(PikaObj *self);
int _MatrixOS_InputCluster_InputCluster_Shape(PikaObj *self);
void _MatrixOS_InputCluster_InputCluster___init__(PikaObj *self);

#endif
