/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_UIButton_UIButton__H
#define ___MatrixOS_UIButton_UIButton__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_UIButton_UIButton(Args *args);

pika_bool _MatrixOS_UIButton_UIButton_OnHold(PikaObj *self, Arg* holdCallback);
pika_bool _MatrixOS_UIButton_UIButton_OnPress(PikaObj *self, Arg* pressCallback);
pika_bool _MatrixOS_UIButton_UIButton_SetColor(PikaObj *self, PikaObj* color);
pika_bool _MatrixOS_UIButton_UIButton_SetColorFunc(PikaObj *self, Arg* colorFunc);
pika_bool _MatrixOS_UIButton_UIButton_SetName(PikaObj *self, char* name);
pika_bool _MatrixOS_UIButton_UIButton_SetSize(PikaObj *self, PikaObj* dimension);
void _MatrixOS_UIButton_UIButton___init__(PikaObj *self);

#endif
