/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___MatrixOS_InputEvent_InputEvent__H
#define ___MatrixOS_InputEvent_InputEvent__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__MatrixOS_InputEvent_InputEvent(Args *args);

int _MatrixOS_InputEvent_InputEvent_ClusterId(PikaObj *self);
PikaObj* _MatrixOS_InputEvent_InputEvent_Id(PikaObj *self);
int _MatrixOS_InputEvent_InputEvent_InputClass(PikaObj *self);
pika_bool _MatrixOS_InputEvent_InputEvent_KeyActive(PikaObj *self);
pika_float _MatrixOS_InputEvent_InputEvent_KeyForce(PikaObj *self);
pika_bool _MatrixOS_InputEvent_InputEvent_KeyHold(PikaObj *self);
int _MatrixOS_InputEvent_InputEvent_KeyState(PikaObj *self);
pika_float _MatrixOS_InputEvent_InputEvent_KeyValue(PikaObj *self, int index);
Arg* _MatrixOS_InputEvent_InputEvent_Keypad(PikaObj *self);
int _MatrixOS_InputEvent_InputEvent_MemberId(PikaObj *self);
pika_bool _MatrixOS_InputEvent_InputEvent___bool__(PikaObj *self);
void _MatrixOS_InputEvent_InputEvent___init__(PikaObj *self);

#endif
