/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __ctypes__H
#define __ctypes__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_ctypes(Args *args);

Arg* ctypes_Test(PikaObj *self);
Arg* ctypes_c_bool(PikaObj *self);
Arg* ctypes_c_buffer(PikaObj *self);
Arg* ctypes_c_byte(PikaObj *self);
Arg* ctypes_c_char(PikaObj *self);
Arg* ctypes_c_char_p(PikaObj *self);
Arg* ctypes_c_double(PikaObj *self);
Arg* ctypes_c_float(PikaObj *self);
Arg* ctypes_c_int(PikaObj *self);
Arg* ctypes_c_long(PikaObj *self);
Arg* ctypes_c_longdouble(PikaObj *self);
Arg* ctypes_c_longlong(PikaObj *self);
Arg* ctypes_c_short(PikaObj *self);
Arg* ctypes_c_size_t(PikaObj *self);
Arg* ctypes_c_ssize_t(PikaObj *self);
Arg* ctypes_c_ubyte(PikaObj *self);
Arg* ctypes_c_uint(PikaObj *self);
Arg* ctypes_c_ulong(PikaObj *self);
Arg* ctypes_c_ulonglong(PikaObj *self);
Arg* ctypes_c_void_p(PikaObj *self);
Arg* ctypes_c_wchar(PikaObj *self);
Arg* ctypes_c_wchar_p(PikaObj *self);
Arg* ctypes_create_string_buffer(PikaObj *self);

#endif
