/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __ctypes_create_string_buffer__H
#define __ctypes_create_string_buffer__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_ctypes_create_string_buffer(Args *args);

int ctypes_create_string_buffer___getitem__(PikaObj *self, int __key);
void ctypes_create_string_buffer___init__(PikaObj *self, int size);

#endif
