/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __ctypes_Test__H
#define __ctypes_Test__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_ctypes_Test(Args *args);

int ctypes_Test_add(PikaObj *self, PikaObj* c_uint1, PikaObj* c_uint2);
int ctypes_Test_dc_cpuapdu_hex(PikaObj *self, int slen, uint8_t* sendbuf, PikaObj* rlen, PikaObj* rcvbuf);
void ctypes_Test_print_rcv(PikaObj *self, PikaObj* rcvbuf);

#endif
