/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __MatrixOSLib__H
#define __MatrixOSLib__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_MatrixOSLib(Args *args);

void MatrixOSLib_Bootloader(PikaObj *self);
void MatrixOSLib_DelayMs(PikaObj *self, int ms);
void MatrixOSLib_ExecuteAPP(PikaObj *self, char* author, char* app_name);
void MatrixOSLib_ExecuteAPPByID(PikaObj *self, int app_id);
int MatrixOSLib_Millis(PikaObj *self);
void MatrixOSLib_OpenSetting(PikaObj *self);
void MatrixOSLib_Reboot(PikaObj *self);

#endif
