# MatrixOS Python Interface - UIComponent
# Base class for UI components

class UIComponent:
    def __init__(self) -> None: ...

    # Lifecycle — refuses to destroy if still attached to a live UI
    def Close(self) -> None: ...

    def SetEnabled(self, enabled: bool) -> bool: ...
    def SetEnableFunc(self, enableFunc: any) -> bool: ...