# MatrixOS Python Interface - SYS
# System functions

def Reboot() -> None: ...
def Bootloader() -> None: ...
def DelayMs(ms: int) -> None: ...
def Millis() -> int64: ...
def Micros() -> int64: ...
def OpenSetting() -> None: ...
def ExecuteAPP(author: str, app_name: str) -> None: ...
def ExecuteAPPByID(app_id: int) -> None: ...