# MatrixOS Python Interface - UI
# Core UI class for creating user interfaces

from MatrixOS_UIComponent import UIComponent
from MatrixOS_Point import Point
from MatrixOS_KeyEvent import KeyEvent
from MatrixOS_Color import Color

class UI:
    def __init__(self, *val) -> None: ...

    # UI control methods
    def Start(self) -> bool: ...
    def SetName(self, name: str) -> bool: ...
    def SetColor(self, color: Color) -> bool: ...
    def ShouldCreatenewLEDLayer(self, create: bool) -> bool: ...

    # Callback setters
    def SetSetupFunc(self, setupFunc: any) -> bool: ...
    def SetLoopFunc(self, loopFunc: any) -> bool: ...
    def SetEndFunc(self, endFunc: any) -> bool: ...
    def SetPreRenderFunc(self, pre_renderFunc: any) -> bool: ...
    def SetPostRenderFunc(self, post_renderFunc: any) -> bool: ...
    def SetKeyEventHandler(self, key_event_handler: any) -> bool: ...

    # UI Component management
    def AddUIComponent(self, uiComponent: UIComponent, xy: Point) -> bool: ...
    def ClearUIComponents(self) -> bool: ...

    # UI control
    def AllowExit(self, allow: bool) -> bool: ...
    def SetFPS(self, fps: int) -> bool: ...