# MatrixOS Python Interface - UI4pxNumber
# 4-pixel font number display component

from _MatrixOS_UIComponent import UIComponent
from MatrixOS_Color import Color

class UI4pxNumber(_MatrixOS_UIComponent.UIComponent):
    def __init__(self) -> None: ...

    # Configuration
    def SetName(self, name: str) -> bool: ...
    def SetColor(self, color: Color) -> bool: ...
    def SetAlternativeColor(self, alternativeColor: Color) -> bool: ...
    def SetDigits(self, digits: int) -> bool: ...
    def SetSpacing(self, spacing: int) -> bool: ...

    # Value Management
    def SetValueFunc(self, getValueFunc: any) -> bool: ...

    # Color Functions
    def SetColorFunc(self, colorFunc: any) -> bool: ...