# MatrixOS Python Interface - UIComponent
# Base class for UI components

class UIComponent:
    def __init__(self) -> None: ...

    def SetEnabled(self, enabled: bool) -> bool: ...
    def SetEnableFunc(self, enableFunc: any) -> bool: ...