from MatrixOS_KeyboardKeycode import KeyboardKeycode

def Tap(keycode: KeyboardKeycode, length_ms: int) -> bool: ...
def Press(keycode: KeyboardKeycode) -> bool: ...
def Release(keycode: KeyboardKeycode) -> bool: ...
def ReleaseAll() -> None: ...