# MatrixOS Python Interface - KeyPad
# Keypad input functions

from MatrixOS_Point import Point
from MatrixOS_KeyInfo import KeyInfo
from MatrixOS_KeyEvent import KeyEvent

# Returns KeyEvent on success or None on timeout/failure
def Get(timeout_ms: int) -> any: ...
# Returns KeyInfo if key exists or None if invalid position
def GetKey(keyXY: Point) -> any: ...
# Returns KeyInfo if key exists or None if invalid ID
def GetKeyByID(keyID: int) -> any: ...
def Clear() -> None: ...
def XY2ID(xy: Point) -> int: ...
# Returns Point on success or None if invalid ID
def ID2XY(keyID: int) -> any: ...