# KeyInfo class for MatrixOS
# Binding of OS/Framework/KeyEvent/KeyInfo.h

from MatrixOS_Framework import KeyState

class KeyInfo:
    """Key information structure containing state and timing data"""
    
    # Constructor
    def __init__(self): ...
    def __del__(self): ...

    # Getter
    def State(self) -> int: ... # Should return KeyState
    def Velocity(self) -> float: ...
    def LastEventTime(self) -> int: ...
    def Hold(self) -> bool: ...
    
    # Methods
    def Active(self) -> bool: ...
    def HoldTime(self) -> int: ...
    
    # Boolean conversion operator
    def __bool__(self) -> bool: ...