# MatrixOS Python Interface — InputCluster
# Read-only snapshot of an input cluster descriptor.

from MatrixOS_Point import Point
from MatrixOS_Dimension import Dimension

class InputCluster:
    def __init__(self): ...
    def ClusterId(self) -> int: ...
    def Name(self) -> str: ...
    def InputClass(self) -> int: ...
    def Shape(self) -> int: ...
    def RootPoint(self) -> Point: ...
    def Dimension(self) -> Dimension: ...
    def InputCount(self) -> int: ...
    def HasRootPoint(self) -> bool: ...
    def HasCoordinates(self) -> bool: ...
