# Dimension class for MatrixOS
# Binding of OS/Framework/Geometry/Dimension.h

from MatrixOS_Point import Point

class Dimension:
    """2D dimension structure containing width and height"""
    
    # Constructor with optional parameters
    # 0 args - Zero dimension (0, 0)
    # 1 int - From raw bytes
    # 2 ints - Width and height
    def __init__(self, *val): ...
    
    # Getters
    def X(self) -> int: ...
    def Y(self) -> int: ...
    
    # Setters
    def SetX(self, x: int) -> None: ...
    def SetY(self, y: int) -> None: ...
    
    # Methods
    def Contains(self, point: Point) -> bool: ...
    def Area(self) -> int: ...
    
    # Operators
    def __add__(self, other: Dimension) -> Dimension: ...
    def __eq__(self, other: Dimension) -> bool: ...
    def __bool__(self) -> bool: ...