# MatrixOS Python Interface - USB
# Binding of OS/MatrixOS.h (USB related functions)

def Connected(self) -> bool: ...

class CDC:
    def Connected(self) -> bool: ...
    def Available(self) -> int: ...
    def Poll(self) -> None: ...
    def Print(self, text: str, end: str) -> None: ...
    def Flush(self) -> None: ...
    def Read(self) -> int: ...
    def ReadBytes(self, length: int) -> bytes: ...
    def ReadString(self) -> str: ...
