# KeyEvent class for MatrixOS
# Binding of OS/Framework/KeyEvent/KeyEvent.h

from MatrixOS_KeyInfo import KeyInfo

class KeyEvent:
    """Key event structure containing key ID and info"""
    
    # Constructor
    def __init__(self): ...

    # Getters
    def ID(self) -> int: ...
    def KeyInfo(self) -> any: ...

    # Pass-through methods to KeyInfo
    def State(self) -> int: ...
    def Hold(self) -> bool: ...
    def HoldTime(self) -> int: ...
    def Active(self) -> bool: ...
    def Force(self) -> float: ...
    def Value(self, index: int = 0) -> float: ...

    # Boolean conversion operator
    def __bool__(self) -> bool: ...