# ColorEffects functions for MatrixOS
# Binding of OS/Framework/Color/ColorEffects.h

from MatrixOS_Color import Color

# Color generation effects
def Rainbow(period: int = 1000, offset: int = 0) -> Color: ...

# Brightness modulation effects (returns 0-255)
def Breath(period: int = 1000, offset: int = 0) -> int: ...
def BreathLowBound(low_bound: int = 64, period: int = 1000, offset: int = 0) -> int: ...
def Strobe(period: int = 1000, offset: int = 0) -> int: ...
def Saw(period: int = 1000, offset: int = 0) -> int: ...
def Triangle(period: int = 1000, offset: int = 0) -> int: ...

# Color modulation effects (applies effect to existing color)
def ColorBreath(color: Color, period: int = 1000, offset: int = 0) -> Color: ...
def ColorBreathLowBound(color: Color, low_bound: int = 64, period: int = 1000, offset: int = 0) -> Color: ...
def ColorStrobe(color: Color, period: int = 1000, offset: int = 0) -> Color: ...
def ColorSaw(color: Color, period: int = 1000, offset: int = 0) -> Color: ...
def ColorTriangle(color: Color, period: int = 1000, offset: int = 0) -> Color: ...