# MatrixOS Python Interface — InputId
# Identifies a specific input (cluster + member).

class InputId:
    def __init__(self): ...

    # Cluster index (0 = function key cluster)
    def ClusterId(self) -> int: ...

    # Member index within the cluster
    def MemberId(self) -> int: ...

    def __eq__(self, other: 'InputId') -> bool: ...
    def __ne__(self, other: 'InputId') -> bool: ...
    def __bool__(self) -> bool: ...

    # Static factory methods
    @staticmethod
    def FunctionKey() -> 'InputId': ...
    @staticmethod
    def Invalid() -> 'InputId': ...
