# MatrixOS Python Interface - LED
# LED control functions

from _MatrixOS_Point import Point
from _MatrixOS_Color import Color

def NextBrightness(self) -> None: ...
def SetBrightness(self, brightness: int) -> None: ...
def SetBrightnessMultiplier(self, partition_name: str, multiplier: float) -> None: ...
def SetColor(self, xy: Point, color: Color, layer:int) -> None: ...
def SetColorByID(self, id: int, color: Color, layer:int) -> None: ...
def Fill(self, color: Color, layer:int) -> None: ...
def FillPartition(self, partition: str, color: Color, layer:int) -> None: ...
def Update(self, layer:int) -> None: ...
def CurrentLayer(self) -> int: ...
def CreateLayer(self, crossfade:int) -> int: ...
def CopyLayer(self, dest: int, src: int) -> None: ...
def DestroyLayer(self, crossfade:int) -> bool: ...
def Fade(self, crossfade:int) -> None: ...
def PauseUpdate(self, pause: bool) -> None: ...
def GetLEDCount(self) -> int: ...