# MatrixOS Python Interface - NVS
# Non-Volatile Storage functions

def GetSize(self, hash: int) -> int: ...
def GetVariable(self, hash: int) -> bytes: ...
def SetVariable(self, hash: int, data: bytes, length:int) -> bool: ...
def DeleteVariable(self, hash: int) -> bool: ...