# MatrixOS Python Interface - KeyPad
# Keypad input functions

from _MatrixOS_Point import Point
from _MatrixOS_KeyEvent import KeyEvent, KeyInfo

def Get(timeout_ms: int) -> KeyEvent: ...
def GetKey(keyXY: Point) -> KeyInfo: ...
def GetKeyByID(keyID: int) -> KeyInfo: ...
def Clear() -> None: ...
def XY2ID(xy: Point) -> int: ...
def ID2XY(keyID: int) -> Point: ...