# KeyInfo class for MatrixOS
# Binding of OS/Framework/KeyEvent/KeyInfo.h

from MatrixOS_KeyState import KeyState

class KeyInfo:
    """Key information structure containing state and timing data"""
    
    # Constructor
    def __init__(self, *val): ...

    # Getters
    def State(self) -> int: ... # Should return KeyState
    def Force(self) -> float: ...
    def Value(self, index: int = 0) -> float: ...
    def LastEventTime(self) -> int: ...
    def Hold(self) -> bool: ...
    
    # Methods
    def Active(self) -> bool: ...
    def HoldTime(self) -> int: ...
    
    # Boolean conversion operator
    def __bool__(self) -> bool: ...