from MatrixOS_SystemKeycode import SystemKeycode

# def Write(keycode: SystemKeycode) -> None: ...
# def Press(keycode: SystemKeycode) -> None: ...
# def Release() -> None: ...
# def ReleaseAll() -> None: ...