# MatrixOS Python Interface - UIButton
# Button UI component with press and hold callbacks

from _MatrixOS_UIComponent import UIComponent
from MatrixOS_Color import Color
from MatrixOS_Dimension import Dimension

class UIButton(_MatrixOS_UIComponent.UIComponent):
    def __init__(self) -> None: ...

    def SetName(self, name: str) -> bool: ...
    def SetColor(self, color: Color) -> bool: ...
    def SetColorFunc(self, colorFunc: any) -> bool: ...
    def SetSize(self, dimension: Dimension) -> bool: ...

    def OnPress(self, pressCallback: any) -> bool: ...
    def OnHold(self, holdCallback: any) -> bool: ...