from MatrixOS_MouseKeycode import MouseKeycode

# def Click(keycode: MouseKeycode) -> None: ...
# def Press(keycode: MouseKeycode) -> None: ...
# def Release(keycode: MouseKeycode) -> None: ...
# def ReleaseAll() -> None: ...
# def MoveTo(x: int, y: int, wheel: int) -> None: ...
# def Move(x: int, y: int, wheel: int) -> None: ...