# Color class for MatrixOS
# Binding of OS/Framework/Types/Color.h

class Color:
    # Constructor with optional parameters
    # 0 Int - Black
    # 1 Int - WRGB
    # 3 int - R, G, B
    # 4 int - R, G, B, W
    def __init__(self, *val): ...
    
    # Static factory methods for different color creation patterns
    def FromRGB(r: int, g: int, b: int) -> Color: ...
    def FromRGBW(r: int, g: int, b: int, w: int) -> Color: ...
    def FromHex(wrgb: int) -> Color: ...

    # Color Getter
    def R(self) -> int: ...
    def G(self) -> int: ...
    def B(self) -> int: ...
    def W(self) -> int: ...
    def RGB(self) -> int: ...
    def WRGB(self) -> int: ...

    # Color Setter
    def SetR(self, r: int) -> None: ...
    def SetG(self, g: int) -> None: ...
    def SetB(self, b: int) -> None: ...
    def SetW(self, w: int) -> None: ...

    # Color manipulation methods
    def Scale(self, factor: float) -> Color: ...
    def Dim(self, factor: float) -> Color: ...
    def DimIfNot(self, not_dim: bool, factor: float) -> Color: ...
    
    # Color operators
    def __eq__(self, other: Color) -> bool: ...
    def __ne__(self, other: Color) -> bool: ...
    
  