from MatrixOS_KeyboardKeycode import KeyboardKeycode

def Write(keycode: KeyboardKeycode) -> bool: ...
def Press(keycode: KeyboardKeycode) -> bool: ...
def Release(keycode: KeyboardKeycode) -> bool: ...
def ReleaseAll() -> None: ...