# MatrixOS Python Interface - USB::CDC
# Binding of OS/MatrixOS.h (USB CDC related functions)

def Connected() -> bool: ...
def Available() -> int: ...
def Poll() -> None: ...
def Print(text: str, end: str) -> None: ...
def Flush() -> None: ...
def Read() -> int: ...
def ReadBytes(max_length: int) -> bytes: ...
def ReadString() -> str: ...
