# MatrixOS Python Interface - UI
# Core UI class for creating user interfaces.
#
# Input capture example:
#
#   ui = MatrixOS.UI("Demo", Color(0xFFFFFF))
#   event = ui.PullInput()
#   if event is not None:
#       cluster_id = event.ClusterId()
#       state = event.KeyState()
#       member_id = event.MemberId()
#
#   ui.Start()

from MatrixOS_UIComponent import UIComponent
from MatrixOS_Point import Point
from MatrixOS_Color import Color

class UI:
    def __init__(self, *val) -> None: ...

    # Lifecycle
    def Start(self) -> None: ...
    def Exit(self) -> None: ...
    def Close(self) -> bool: ...

    # Configuration
    def SetName(self, name: str) -> None: ...
    def SetColor(self, color: Color) -> None: ...
    def ShouldCreatenewLEDLayer(self, create: bool) -> None: ...

    # Callback setters (return bool indicating success).
    def SetSetupFunc(self, setupFunc: any) -> bool: ...
    def SetLoopFunc(self, loopFunc: any) -> bool: ...
    def SetEndFunc(self, endFunc: any) -> bool: ...
    def SetPreRenderFunc(self, pre_renderFunc: any) -> bool: ...
    def SetPostRenderFunc(self, post_renderFunc: any) -> bool: ...

    # Pull one queued keypad input code, or -1 when the queue is empty.
    # Most apps should use MatrixOS_UI.UI.PullInput(), which wraps this as
    # KeyEvent or None.
    def PullInputCode(self) -> int: ...

    # UI Component management
    def AddUIComponent(self, uiComponent: UIComponent, xy: Point) -> None: ...
    def ClearUIComponents(self) -> None: ...

    # UI control
    def AllowExit(self, allow: bool) -> None: ...
    def SetFPS(self, fps: int) -> None: ...
