from MatrixOS_GamepadDPadDirection import GamepadDPadDirection

def Press(button_id: int) -> None: ...
def Release(button_id: int) -> None: ...
def ReleaseAll() -> None: ...
def Button(button_id: int, state: bool) -> None: ...
def Buttons(button_mask: int) -> None: ...
def XAxis(value: int) -> None: ...
def YAxis(value: int) -> None: ...
def ZAxis(value: int) -> None: ...
def RXAxis(value: int) -> None: ...
def RYAxis(value: int) -> None: ...
def RZAxis(value: int) -> None: ...
def DPad(direction: GamepadDPadDirection) -> None: ...