from MatrixOS_ConsumerKeycode import ConsumerKeycode

# def Write(keycode: ConsumerKeycode) -> None: ...
# def Press(keycode: ConsumerKeycode) -> None: ...
# def Release(keycode: ConsumerKeycode) -> None: ...
# def ReleaseAll() -> None: ...