# MatrixOS Python Interface - KeyPad
# Keypad input functions

from _MatrixOS_Point import Point
from _MatrixOS_KeyEvent import KeyEvent, KeyInfo

def Get(self, timeout_ms: int) -> KeyEvent: ...
def GetKey(self, keyXY: Point) -> KeyInfo: ...
def GetKeyByID(self, keyID: int) -> KeyInfo: ...
def Clear(self) -> None: ...
def XY2ID(self, xy: Point) -> int: ...
def ID2XY(self, keyID: int) -> Point: ...