# Color class for MatrixOS
# Binding of OS/Framework/Types/Color.h

class Color:
    # Constructor with optional parameters (defaults to black)
    def __init__(self, r: int, g: int, b: int, w: int): ...
    
    # Static factory methods for different color creation patterns
    def FromRGB(r: int, g: int, b: int) -> Color: ...
    def FromRGBW(r: int, g: int, b: int, w: int) -> Color: ...
    def FromHex(hex: int) -> Color: ...

    # Color properties
    r: int
    g: int
    b: int
    w: int
    
    # Color manipulation methods
    def Scale(self, factor: float) -> Color: ...
    def Dim(self, factor: float) -> Color: ...
    def DimIfNot(self, not_dim: bool, factor: float) -> Color: ...
    
    # Color operators
    def __eq__(self, other: Color) -> bool: ...
    def __ne__(self, other: Color) -> bool: ...
    
  