# MatrixOS Python Interface - LED
# LED control functions

from MatrixOS_Point import Point
from MatrixOS_Color import Color

def NextBrightness() -> None: ...
def SetBrightness(brightness: int) -> None: ...
def SetBrightnessMultiplier(partition_name: str, multiplier: float) -> bool: ...
def SetColor(xy: Point, color: Color, layer:int) -> None: ...
def SetColorByID(id: int, color: Color, layer:int) -> None: ...
def Fill(color: Color, layer:int) -> None: ...
def FillPartition(partition: str, color: Color, layer:int) -> bool: ...
def Update(layer:int) -> None: ...
def CurrentLayer() -> int: ...
def CreateLayer(crossfade:int) -> int: ...
def CopyLayer(dest: int, src: int) -> None: ...
def DestroyLayer(crossfade:int) -> bool: ...
def Fade(crossfade:int) -> None: ...
def PauseUpdate(pause: bool) -> None: ...
def GetLEDCount() -> int: ...