# Point class for MatrixOS
# Binding of OS/Framework/Point/Point.h

from _MatrixOSDirection import Direction

class Point:
    """2D coordinate point structure"""
    
    x: int
    y: int

    def __init__(self, x: int, y: int): ...
    def __add__(self, other: Point) -> Point: ...
    def __sub__(self, other: Point) -> Point: ...
    def __mul__(self, val: int) -> Point: ...
    def __div__(self, val: int) -> Point: ...
    def __eq__(self, other: Point) -> bool: ...
    def __ne__(self, other: Point) -> bool: ...
    def Rotate(self, rotation: Direction, dimension: Point, reverse: bool) -> Point: ...

    def Origin() -> Point: ...
    def Invalid() -> Point: ...