# MatrixOS Python Interface - UIUtility
# UI utility functions for common interface patterns

from MatrixOS_Color import Color

def TextScroll(text: str, color: Color, speed: int, loop: bool) -> None: ...
def NumberSelector8x8(value: int, color: Color, name: str, lower_limit: int, upper_limit: int) -> int: ...
def ColorPicker() -> any: ...