# MatrixOS Python Interface — KeypadInfo
# Provides keypad-specific state for a single input.

class KeypadInfo:
    def __init__(self): ...

    # KeypadState enum value (see MatrixOS_KeyState)
    def State(self) -> int: ...

    # Pressure / force value (0.0–1.0)
    def Force(self) -> float: ...

    # Generic value accessor (0 = pressure, 1 = velocity)
    def Value(self, index: int) -> float: ...

    # Timestamp of last state change (milliseconds)
    def LastEventTime(self) -> int: ...

    # True if the key is being held
    def Hold(self) -> bool: ...

    # True if the key is in an active state (pressed/hold/aftertouch/released)
    def Active(self) -> bool: ...

    # Duration the key has been held (milliseconds), 0 if not active
    def HoldTime(self) -> int: ...

    def __bool__(self) -> bool: ...
