from MatrixOS_GamepadDPadDirection import GamepadDPadDirection

def Tap(button_id: int, length_ms: int) -> None: ...
def Press(button_id: int) -> None: ...
def Release(button_id: int) -> None: ...
def ReleaseAll() -> None: ...
def Button(button_id: int, state: bool) -> None: ...
def Buttons(button_mask: int) -> None: ...
def XAxis(value: float) -> None: ...
def YAxis(value: float) -> None: ...
def ZAxis(value: float) -> None: ...
def RXAxis(value: float) -> None: ...
def RYAxis(value: float) -> None: ...
def RZAxis(value: float) -> None: ...
def DPad(direction: GamepadDPadDirection) -> None: ...