# MIDI status constants.
NONE = 0
NOTE_OFF = 128
NOTE_ON = 144
AFTERTOUCH = 160
CONTROL_CHANGE = 176
PROGRAM_CHANGE = 192
CHANNEL_PRESSURE = 208
PITCH_CHANGE = 224
MTC_QUARTER_FRAME = 241
SONG_POSITION = 242
SONG_SELECT = 243
TUNE_REQUEST = 246
SYNC = 248
TICK = 249
START = 250
CONTINUE = 251
STOP = 252
ACTIVE_SENSE = 254
RESET = 255
SYSEX_DATA = 240
SYSEX_END = 247

class MidiStatus:
    NONE: int = NONE
    NoteOff: int = NOTE_OFF
    NoteOn: int = NOTE_ON
    AfterTouch: int = AFTERTOUCH
    ControlChange: int = CONTROL_CHANGE
    ProgramChange: int = PROGRAM_CHANGE
    ChannelPressure: int = CHANNEL_PRESSURE
    PitchChange: int = PITCH_CHANGE
    MTCQuarterFrame: int = MTC_QUARTER_FRAME
    SongPosition: int = SONG_POSITION
    SongSelect: int = SONG_SELECT
    TuneRequest: int = TUNE_REQUEST
    Sync: int = SYNC
    Tick: int = TICK
    Start: int = START
    Continue: int = CONTINUE
    Stop: int = STOP
    ActiveSense: int = ACTIVE_SENSE
    Reset: int = RESET
    SysExData: int = SYSEX_DATA
    SysExEnd: int = SYSEX_END
