# MIDI port constants.
EACH_CLASS = 0x0
ALL = 0x01
USB = 0x100
PHYSICAL = 0x200
BLUETOOTH = 0x300
WIRELESS = 0x400
RTP = 0x500
DEVICE_CUSTOM = 0x600
SYNTH = 0x8000
INVALID = 0xFFFF

class MidiPortID:
    MIDI_PORT_EACH_CLASS: int = EACH_CLASS
    MIDI_PORT_ALL: int = ALL
    MIDI_PORT_USB: int = USB
    MIDI_PORT_PHYSICAL: int = PHYSICAL
    MIDI_PORT_BLUETOOTH: int = BLUETOOTH
    MIDI_PORT_WIRELESS: int = WIRELESS
    MIDI_PORT_RTP: int = RTP
    MIDI_PORT_DEVICE_CUSTOM: int = DEVICE_CUSTOM
    MIDI_PORT_SYNTH: int = SYNTH
    MIDI_PORT_INVALID: int = INVALID
