if(NOT DEFINED ENV{IDF_PATH})
  message(FATAL_ERROR " Please set up ESP-IDF environment before building.")
endif()

message(STATUS "IDF_PATH: $ENV{IDF_PATH}")
include($ENV{IDF_PATH}/tools/cmake/project.cmake)

set(SDKCONFIG ${CMAKE_BINARY_DIR}/sdkconfig)

string(TOUPPER "${IDF_TARGET}" TINYUSB_MCU_OPT)

if(MODE STREQUAL "RELEASE")
    set(SDKCONFIG_DEFAULTS ${FAMILY_PATH}/sdkconfig.release)
elseif(MODE STREQUAL "RELEASECANDIDATE")
    set(SDKCONFIG_DEFAULTS ${FAMILY_PATH}/sdkconfig.release)
elseif(MODE STREQUAL "BETA")
    set(SDKCONFIG_DEFAULTS ${FAMILY_PATH}/sdkconfig.release)
elseif(MODE STREQUAL "NIGHTLY")
    set(SDKCONFIG_DEFAULTS ${FAMILY_PATH}/sdkconfig.release)
elseif(MODE STREQUAL "DEVELOPMENT")
    set(SDKCONFIG_DEFAULTS ${FAMILY_PATH}/sdkconfig.development)
elseif(MODE STREQUAL "UNDEFINED")
    set(SDKCONFIG_DEFAULTS ${FAMILY_PATH}/sdkconfig.development)
else()
    set(SDKCONFIG_DEFAULTS ${FAMILY_PATH}/sdkconfig.development)
endif()